
name: Run Python Script each 3rd hour

on:
  schedule:
    - cron: "0 */1 * * *"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytz
        python -m pip install requests
        python -m pip install feedparser
        python -m pip install beautifulsoup4
        python -m pip install firebase-admin
        
        
    - name: Run Telegram RSS Feed
      run: python3 telegram_rss_feed.py ${{secrets.TELEGRAM_BOT_TOKEN}} ${{secrets.TELEGRAM_CHANNEL_ID}}
